if: tag IS blank

language: node_js

node_js:
  - "14"
  - "16"
  - "18"

jobs:
  include:
    - stage: test
      name: "Unit tests, type checking, linting, etc."
      script:
        - yarn check-types
        - yarn test
        - git reset --hard HEAD
        - yarn check-formatting
        - yarn build
        - yarn commitlint-travis
    - stage: release
      branches:
        only:
          - master
      node_js: 18
      name: "Release on npm"
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn semantic-release
